### PR TITLE
Feature/build network

### PR DESCRIPTION
**Pull request by spencerrecneps**
This removes the need for the TDG Tools extension by pulling the network building into a script. I didn't want to touch the VM setup, but there's no longer a need to pull TDG Tools from my repo.

This partially resolves https://github.com/azavea/pfb-network-connectivity/issues/154

### CODE REVIEW

**Comment by CloudNiner** [comment]
What is the reasoning for this change? After browsing the source for those TDG functions, it looks mostly the same.

**Comment by CloudNiner** [comment]
The TDG Tools can be removed from the VM setup by deleting lines 47-48 in the `pfb-analysis/Dockerfile`:

https://github.com/azavea/pfb-network-connectivity/blob/develop/pfb-analysis/Dockerfile#L47

**Comment by spencerrecneps** [comment]
You're correct that it's mostly the same. I basically took the TDG Tools code and copied it wholesale into the scripts here.

The primary purpose was to remove dependency on TDG Tools, which was never really intended to be part of the PFB source. It will be better to keep all functionality contained within the PFB repo.

**Comment by CloudNiner** [comment]
Gotcha. The major disadvantage of this is that you're now copying code if you want the same functionality in TDGTools as the PFB repo. If its an issue of open sourcing, then adding a LICENSE to TDGTools (if one doesn't exist) should be sufficient. 

We could modify the Dockerfile build that pulls the TDGTools SQL code to always specify a particular commit. That way you could leave all the code in one place and continue developing on whatever branch you want, without the danger of accidentally deploying changes before they're ready.

Either way, if you're willing to handle the maintenance burden of two duplicate codebases, and/or TDGTools won't be used for anything going forward (i.e. it's only purpose was to eventually be merged into PFB) then we can merge this. I would just urge caution before taking on that burden, depending on your future plans, as it could very quickly become unsustainable.

**Comment by spencerrecneps** [comment]
The functionality here is simply building a routable road network. It's a small piece of the TDG Tools suite, which I'm not sure we as a firm want to publicize. (It's obviously discoverable right now but we'd prefer not to trumpet its existence to the world.)

Apart from any bugs in the way it builds the network, I don't foresee making any changes. It's a very specific piece of functionality that I wouldn't be planning to add features to even if I made changes in the original codebase.

**Pull request merged**
