### PR TITLE
Feature/connectivity performance improvements

### PR DESCRIPTION
**Pull request by spencerrecneps**
I don't think it's possible to submit a PR that proposes a new branch, but this should remain in a separate branch for now. I can resubmit if it's easier to create a new branch and have me create a new PR.

These changes relate to https://github.com/azavea/pfb-network-connectivity/issues/74. Since I can't run the full thing on my Windows machine I'd like to have someone test this for performance improvements. 

For large neighborhood areas memory usage might be extremely large. In addition, I'm not sure there's a way to parallelize this. If performance improvements are significant enough, we'd need to test on a large area in the target environment to make sure it's still feasible.

### CODE REVIEW

**Comment by CloudNiner** [comment]
Thanks for taking a look at this. We're working out some issues with the analysis jobs in development, and building out the environment to run these jobs on AWS. Will likely take a look at this PR once we've got those tasks ironed out. We'll revisit this PR once we've got those other tasks ironed out.

**Comment by spencerrecneps** [comment]
I ran a quick test using the same base data from Cambridge and came up with the following results for elapsed time on reachable_roads_high_stress_calc.sql with a neighborhood buffer of 5000 ft:

With pgr_johnson (modified code in this PR):
Run 1 - 3:32.34
Run 2 - 3:12.95
Run 3 - 3:17.35
Run 4 - 2:57.21
Run 5 - 2:50.93

Existing code:
Run 1 - 4:45.24
Run 2 - 3:54.56
Run 3 - 3:43.94
Run 4 - 3:51.18
Run 5 - 3:44.36

Please note that the existing code did not make use of multiple cores in my testing, so it's possible the performance improvement with pgr_johnson is offset by the ability to distribute the load among cores.

**Comment by CloudNiner** [comment]
Thanks for running these tests. Can you clarify whether the "existing code" measurements are from the current `develop` branch (has the multithreading) or from some older branch that uses the single-threaded implementation, before we made those performance improvements?

**Comment by spencerrecneps** [comment]
I removed the multithreaded parts of the code to run the analysis. I wasn't totally sure how to use the threads in a standalone process and I'm not actually sure how many threads are available on our server anyway.

As I mentioned, it's possible that multithreading can end up closing the performance gap. It's also possible that the performance gap can widen on larger datasets. The pgr_johnson algorithm works by essentially dumping a snapshot of the entire graph into a table. Our current approach mimics this by doing the driving distance analysis node-by-node and dumping the results to a table.

My suspicion is that the added processing time on a large dataset for pgr_johnson is a linear function, whereas the added processing time in the current setup is exponential. Unfortunately, pgr_johnson imposes higher requirements for RAM since you're storing the whole graph in memory and I haven't been able to test larger areas--it crashes our server, which runs out of available memory.

**Comment by CloudNiner** [comment]
Ok. So in that case, for smaller areas at least, the existing solution is better, as we see a 2-3.5x speedup with the multithreaded version. So for initial testing, we'll continue forward with the existing strategy.

With that said, we could use AWS instance types with more RAM, so it might be worth testing down the road. How much RAM does your server have?

**Comment by CloudNiner** [comment]
Also note that the high/low stress SQL files are not the ones that take the longest. The SQL script with the most running time is the `connected_census_blocks`, so further optimization should be focused there.

For example, for Boulder, the high/low scripts run in about ~5min, but `connected_census_blocks.sql` takes ~1hr. So small improvements to high/low connectivity mean much less than a similar improvement to connected_census_blocks.

**Comment by spencerrecneps** [comment]
Our server has 10 GB of RAM.

Good point about optimizing connected_census_blocks.sql. I'll focus future efforts there. We can let this PR sit and perhaps do some testing later.

**Comment by spencerrecneps** [comment]
See https://github.com/azavea/pfb-network-connectivity/pull/153

**Comment by CloudNiner** [comment]
This PR is very out of date, and the optimizations made here were unnecessary for most analyses. If desired, this change can be investigated in a later phase of the project. Closing.

**Pull request closed without merging**
