### PR TITLE
Feature/awf/tile style updates#513

### LINKED ISSUE #513: Change map color ramp
High stress as red and low stress as dark grey (see below). 
 
PROCESS BLACK 85%
CMYK 0/0/0/85
RGB 72/71/72
HEX 4c4c4e

### LINKED ISSUE #521: Update bike infrastructure layer color scheme
Updated color scheme as follows:

- `FUNCTIONAL='path'` = `#15bf50` -- thinner line (same as bike lane)
- `FT/TF_BIKE_IN=track` = `#44a3a6` -- fattest line (~twice the thickness of bike lane)
- `FT/TF_BIKE_IN=buffered_lane` = `#5072f5` -- fatter line (~1.5 times the thickness of bike lane)
- `FT/TF_BIKE_IN=lane` = `#8c54de` -- thinner line

No dashes or other fancy effects needed on any of the layers.

### PR DESCRIPTION
**Pull request by CloudNiner**
## Overview

Updates the tile layer styles to what was requested by PFB in #513, #521. Changes applied for ways, census_blocks and bike infrastructure.

### Demo

A full set of screenshots for the changes for the ways and census blocks layers is [available here](https://github.com/azavea/pfb-network-connectivity/issues/513#issuecomment-314763733).

Demo of the bike infrastructure layer changes is [here](https://github.com/azavea/pfb-network-connectivity/issues/521#issuecomment-314825195) and [here](https://github.com/azavea/pfb-network-connectivity/pull/520).

In addition, you can look at the changed PNG thumbnails in this diff to get a side-by-side comparison of the changes in each layer.

## Testing Instructions
 * Build tilemaker container with `docker-compose build tilemaker`
 * Re-run tilemaker for an existing tile job or create and complete a new AnalysisJob
 * View changed layer styles on the neighborhood detail view via the map layer switcher.

Closes #513, Closes #521

### CODE REVIEW

**Comment by KlaasH** [comment]
The gradient with gray in the middle makes more sense, but it seems like it's backwards.  Ways and census blocks are both setting high as red and low as blue, but the values are "stress" for ways and "low-stress connectivity" for blocks, so to align the meanings of the colors the census blocks color ramp should be reversed.

**Comment by CloudNiner** [comment]
Oh crap. :facepalm:

**Comment by CloudNiner** [comment]
Updated:

screen shot 2017-07-13 at 08 58 41

**Comment by CloudNiner** [comment]
Updated:

screen shot 2017-07-13 at 08 58 41

**Pull request merged**
