### PR TITLE
Provision successfully on Windows

### PR DESCRIPTION
**Pull request by CloudNiner**
## Overview

@spencerrecneps will begin working on our forked repository rather than his original upstream source. This requires that he be able to run the analysis from a Windows host. This PR updates the repo with instructions and changes to support this. I tested the setup instructions through building the Docker pfb container in the VM.

## Demo

screenshot 1

## Notes

Includes commit to switch to Ansible local-provisioning. Supersedes #66 

Changes to make so far:
- [x] Add instruction to create the `~/.aws` dir and generate credentials if they don't exist
- [x] Add instruction to `cd ./pfb-analysis` before manually running `docker build`

## Testing

Gotta have a Windows host. If you do, install everything and follow the README instructions.

Connects #63

### CODE REVIEW

**Comment by spencerrecneps** [comment]
Getting an error on ./scripts/setup: 

image

Is this a dependency that isn't listed?

**Comment by spencerrecneps** [comment]
Sorry, forgot to tag @CloudNiner

**Comment by CloudNiner** [comment]
No problem, I see all notifications to this repo without the tagging, was just out yesterday afternoon :)

Whoops. You can just create that folder for now, I'll update the README with instructions for setting up AWS credentials before merging though. On Windows that folder would probably be `C:\Users\username\.aws`, should be fine to `mkdir` it in the git bash prompt.

**Comment by spencerrecneps** [comment]
New error:

image

Looks to be related to NFS?

**Comment by CloudNiner** [comment]
Note this item in the "windows specific notes" section:

https://github.com/azavea/pfb-network-connectivity/pull/69/files#diff-04c6e90faac2675aa89e2176d2eec7d8R15

I didn't provide more details there because the way to set this ENV variable differs depending on which console you use. If you're using the git bash console, you should be able to do `PFB_SHARED_FOLDER_TYPE=virtualbox ./scripts/server` or `export PFB_SHARED_FOLDER_TYPE=virtualbox && ./scripts/server`. If you're not using git bash shell, I'm not sure how to set it actually, I'm relatively unfamiliar with Windows cmd.exe.

If `PFB_SHARED_FOLDER_TYPE=virtualbox` fails, try `PFB_SHARED_FOLDER_TYPE=vboxsf` instead. Let me know which of the two works.

**Comment by spencerrecneps** [comment]
Ah, sorry. I did that yesterday and then forgot that detail this morning.

**Comment by spencerrecneps** [comment]
New error after the process runs smoothly for quite a while:

image

Looks to be a DOS line ending issue?

**Comment by CloudNiner** [comment]
It certainly does. I expected [this configuration](https://github.com/azavea/pfb-network-connectivity/pull/69/files#diff-fc723d30b02a4cca7a534518111c1a66R1) to take care of this, but that doesn't seem to be the case. I don't think I had this happen to me, but I originally set `git config --global core.autocrlf input` at my command line before checking the repository out. Did you modify `./scripts/update` at all? Are the unsaved changes in the git index? (run `git status`) 

For this project it might also be necessary to set whatever editor you're using to force saving using LF instead of CRLF, since a bunch of editors will by default swap the line endings when you first open the file, git won't fix these via the .gitattributes setting mentioned above until you commit.

**Comment by spencerrecneps** [comment]
No unsaved changes via git status. I didn't make any changes to ./scripts/update but I did open the project in Atom on Windows at some point. I'll start from scratch and see if that fixes it.

**Comment by CloudNiner** [comment]
Ok. 🤞

**Comment by spencerrecneps** [comment]
Still didn't work until I ran ./scripts/update through dos2unix. That seems to have fixed it. Will send PR. I'm now getting an error when I try to run the analysis.with

`docker build -t pfb .`

image

I skipped to "Running the Analysis" instead of setting up the server as directed by the docs but I'm not sure if that's relevant.

**Comment by CloudNiner** [comment]
Shoot. Might have missed another change. Can you `cd /vagrant/pfb-analysis` and then re-run the Docker command? That command would need to be run from whatever dir contains the Dockerfile you want to build, which in this case is `./pfb-analysis/Dockerfile`.

**Comment by spencerrecneps** [comment]
Weird. That folder is empty for me. Do I need to do something in my clone to grab the subrepo as well?

**Comment by CloudNiner** [comment]
Yes. Two options:
1. On initial clone, you can do `git clone --recursive git@github.com:azavea/pfb-network-connectivity.git`
2. If you've already checked out the repo, you can do `git submodule init && git submodule update` to checkout the appropriate submodule commit.

This will be going away as soon as #71 is merged (which will hopefully be today).

**Comment by spencerrecneps** [comment]
That line ending issue must be a bug in Git for Windows or something. If I clone in Linux the line ending issue doesn't exist. Furthermore, when I fix it with dos2unix and then run git status it shows that the file has changed but when I add, commit, and push it tells me there were no changes.

**Comment by spencerrecneps** [comment]
`docker build -t pfb .` works in ./pfb-analysis. I'm now getting errors on the `docker run` command:
> /pfb/entrypoint.sh: not found

This occurs whether I run it from ./pfb-analysis or from .

image

**Comment by CloudNiner** [comment]
Hmm. I have not seen this. Does the file `./pfb-analysis/entrypoint.sh` exist on the filesystem inside the VM? I wonder if theres an issue here where the submodule wasn't properly checked out? What's the output of `git log` when run within the `./pfb-analysis` dir?

You can run the `docker run` command in the `/vagrant` folder, once the image exists, `docker run` associates the image to run by the `pfb` tag you see in the docker run command.

I'm a bit surprised by the line endings issue. I would also expect that to be properly cleaned up by git at this point. Let us know if it becomes a recurring issue.

**Comment by spencerrecneps** [comment]
There is a file named `entrypoint.sh` in `./pfb-analysis`. I see a reference to `/pfb/entrypoint.sh` in the Dockerfile, is it possible this is a bad path?

**Comment by spencerrecneps** [comment]
Output of `git log` attached.
[gitlog.txt](https://github.com/azavea/pfb-network-connectivity/files/778270/gitlog.txt)

**Comment by CloudNiner** [comment]
Your `git log` has the expected output. Not sure what it is. 

So I just rebased this branch against current develop, which just had the PR merged into it which removes the submodule. It also looks like as fallout to that there were some files committed into the subproject with CRLF line endings. This PR strips those from the remaining files. Maybe some of your issues are transient issues with that? We don't need windows line endings anymore since all files will be expected to be run within a linux environment (on the Docker container). 

So to update, do the following:
```
vagrant destroy
git checkout develop
git branch -D feature/awf/provision-on-windows
rm -rf pfb-analysis
git pull
git checkout feature/awf/provision-on-windows
# At this point your git repo should be reset, with the up-to-date HEAD of this feature branch
# You should be able to follow the README instructions from the start, starting with...
./scripts/setup
```

Hope this does it, as you can see we're in active development. I'll try running this through again myself from scratch on my windows machine when I get home.

**Comment by spencerrecneps** [comment]
Heh. I opted for the [xkcd approach](https://xkcd.com/1597/). Should have waited for your instructions.

**Comment by spencerrecneps** [comment]
Hmm. New error while provisioning. Looks like something related to `azavea.aws-cli`.

image

**Comment by CloudNiner** [comment]
Are you running this in a prompt with administrator privileges? 

If not, you'll want to `vagrant destroy` what was built in the non-elevated prompt before switching to an elevated prompt. Otherwise, Virtualbox will complain about a user not owning the VM attempting to control it. I ran into this yesterday while testing.

**Comment by spencerrecneps** [comment]
Bingo. I had reopened bash without admin. Did I mention how much I hate doing anything remotely technical in Windows?

**Comment by CloudNiner** [comment]
Heh, it can be frustrating at times...but glad that's resolved. I'll run through this one more time myself, let me know if you run into any more issues. Good luck!

**Comment by spencerrecneps** [comment]
Still getting the error on calling `entrypoint.sh`

**Comment by CloudNiner** [comment]
Ugh, I was able to reproduce this this am on Windows but not Mac/Linux and I didn't have enough time to look at it in detail, but I have one or two ideas. Unfortunately I don't think I can look at it again until Tuesday. Does that significantly block progress on your end?

**Comment by spencerrecneps** [comment]
That should be OK. I'm still able to test changes to the SQL code on my existing databases.

**Comment by CloudNiner** [comment]
@spencerrecneps I spent some time looking at this again this am. The docker error is misdirection. Can you ssh into your VM and paste the output of `file pfb-analysis/scripts/entrypoint.sh`? If it mentions CRLF line endings, then thats the issue, the bash interpreter fails due to CR characters in the bash scripts.

There are a few ways around this, and I'm not sure what the best one is. For me, it was trivial to delete the repo, then run `git config --global core.autocrlf false` which means git doesn't touch line endings ever. However, if you have other projects checked out, this will affect them too. Alternatively, you can checkout the project, cd into the repo dir, then do `git config core.autocrlf false` to only modify that setting for this project. If you do that, you may have to manually change all files that are already checked out to LF. 

For some reason the .gitattributes change in this PR doesn't seem to have any effect. If I check out the repo with default settings, then the CRLFs are in the text files in the project.

Hope this helps, once I made the global config change, re-checked out the repo, and let the vagrant provisioner do its thing, I was able to successfully run an analysis on windows.

**Comment by CloudNiner** [comment]
@spencerrecneps bumping this. Have you had a chance to give this another shot?

**Comment by spencerrecneps** [comment]
Sorry. Have not tested again. Might have to wait until Monday.

**Comment by spencerrecneps** [comment]
I was able to run the analysis successfully. I like the timing report on the psql calls. That's very helpful for optimization.

**Comment by CloudNiner** [comment]
Great! Glad it worked for you.

**Comment by CloudNiner** [comment]
@sharph ready for your review

**Comment by sharph** [comment]
@CloudNiner Sorry I couldn't get this yesterday, but it probably would have been nice to have review from someone else on our team or someone from ops before merging.

**Pull request merged**
