### PR TITLE
print styling

### PR DESCRIPTION
**Pull request by designmatty**
## Overview

Adds print styling for the place overview page.

### Demo
screen shot 2017-06-12 at 11 47 48 am

### Notes
Page breaks might happen in the middle (vertically cut in half) of a word and unfortunately there is no good way to handle those situations.

## Testing Instructions

 * Go to place overview page
 * click on print icon

Connects #454

### CODE REVIEW

**Comment by CloudNiner** [comment]
It looks like at least FF/Chrome/Safari leave 'print backgrounds' unchecked by default, I'm not sure if its possible to update the header such that it looks correct without print backgrounds checked. Firefox styles also seem more generally busted than the other two browsers. Should also verify general correctness in IE11/Edge.

Here's what I got in each of the browsers:
Chrome (backgrounds checked):
screen shot 2017-06-16 at 08 46 39


Chrome (backgrounds unchecked):
screen shot 2017-06-16 at 08 46 32


Firefox:
[pfb-print-firefox.pdf](https://github.com/azavea/pfb-network-connectivity/files/1080816/pfb-print-firefox.pdf)


Safari:
[pfb-print-safari.pdf](https://github.com/azavea/pfb-network-connectivity/files/1080817/pfb-print-safari.pdf)

**Comment by designmatty** [comment]
It's not possible to force printing backgrounds. The only thing we could do is just hide the navbar completely.

**Comment by CloudNiner** [comment]
Indeed. I'm ok with that. Are the issues in Firefox also background printing issues?

**Comment by designmatty** [comment]
Had a conversation off github about this... The firefox issues are unknown haha. I'm going to be spending some time tomorrow to try and fix it.

**Comment by designmatty** [comment]
Firefox:
screen shot 2017-07-26 at 10 44 26 am

Safari:
screen shot 2017-07-26 at 10 44 53 am

chrome:
screen shot 2017-07-26 at 10 45 02 am

**Pull request merged**
