### PR TITLE
Add check for zero in denominator on neighborhood_overall_scores.sql

### PR DESCRIPTION
**Pull request by spencerrecneps**
## Overview

This addresses https://github.com/azavea/pfb-network-connectivity/issues/370 by adding a check for conditions that would result in a zero in the denominator in the overall scores.

### Notes

**Please note**: I have not tested this but wanted to push this out quickly so you can keep moving on scores. I can test next week if you don't have an opportunity to get to it before I do.

## Testing Instructions

 * Run scores for area with known division by zero
 * Check for div/zero errors
 * Run scores for area that ran successfully
 * Check score results to make sure they match

### CODE REVIEW

**Comment by CloudNiner** [comment]
@spencerrecneps any updates on this?

**Comment by spencerrecneps** [comment]
Apologies. I've been at a conference until this afternoon. Will prioritize testing for tomorrow morning.

**Comment by CloudNiner** [comment]
Closes #370

**Comment by spencerrecneps** [comment]
I checked results. No change to numbers where features are present. No div/0 errors when features are not present.

**Comment by CloudNiner** [comment]
Great, thanks!

**Pull request merged**
