### PR TITLE
Update header text on home page.

### PR DESCRIPTION
**Pull request by spencerrecneps**
## Overview

Changes header text on home page based on request from PFB.

### CODE REVIEW

**Comment by CloudNiner** [comment]
Presumably this PR is also still relevant correct?

**Comment by CloudNiner** [comment]
@spencerrecneps bump. See above ^^

**Comment by spencerrecneps** [comment]
Looks to me like this text has already been changed on the main website, so I think this can be ignored. Wasn't this one of the "emergency" changes that you had to make shortly after publishing the website?

**Comment by CloudNiner** [comment]
So it is. Closing, already applied in a97a1366542396a963c3f03ccb04ea2042037db5

**Pull request closed without merging**
